import {
  Building2,
  Car,
  Coffee,
  Fence,
  Flame,
  Heater,
  MountainSnow,
  Sun,
  Trees,
  Tv,
  UtensilsCrossed,
  Warehouse,
  WashingMachine,
  Wifi,
  Zap,
} from "lucide-react";

/** Icon per `ListingOptions.amenities` message key (resolved via `optionKeyFor`). */
export const AMENITY_ICONS: Record<string, React.ElementType> = {
  ski_in_out: MountainSnow,
  ski_storage: Warehouse,
  backup_generator: Zap,
  fireplace: Flame,
  parking: Car,
  wifi: Wifi,
  central_heating: Heater,
  heating: Heater,
  tv: Tv,
  washing_machine: WashingMachine,
  dishwasher: WashingMachine,
  full_kitchen: UtensilsCrossed,
  kitchen: UtensilsCrossed,
  coffee_maker: Coffee,
  no_balcony: Fence,
  french_balcony: Fence,
  standard_balcony: Fence,
  large_terrace: Sun,
  yard: Trees,
  bbq: Flame,
  complex_management: Building2,
};
