// All Georgian cities + municipal centers (nominative). Bakuriani pinned first;
// remaining 64 are the 5 self-governing cities + 59 controlled municipal centers,
// in Georgian alphabetical order. Sourced from the official list of Georgian
// municipalities. Occupied-territory municipalities are intentionally excluded.
export const GEORGIAN_CITIES = [
  "ბაკურიანი",
  "აბაშა",
  "ადიგენი",
  "ამბროლაური",
  "ასპინძა",
  "ახალქალაქი",
  "ახალციხე",
  "ახმეტა",
  "ბათუმი",
  "ბაღდათი",
  "ბოლნისი",
  "ბორჯომი",
  "გარდაბანი",
  "გორი",
  "გურჯაანი",
  "დედოფლისწყარო",
  "დმანისი",
  "დუშეთი",
  "ვანი",
  "ზესტაფონი",
  "ზუგდიდი",
  "თბილისი",
  "თელავი",
  "თეთრიწყარო",
  "თერჯოლა",
  "თიანეთი",
  "კასპი",
  "ლაგოდეხი",
  "ლანჩხუთი",
  "ლენტეხი",
  "მარნეული",
  "მარტვილი",
  "მესტია",
  "მცხეთა",
  "ნინოწმინდა",
  "ოზურგეთი",
  "ონი",
  "რუსთავი",
  "საგარეჯო",
  "სამტრედია",
  "საჩხერე",
  "სენაკი",
  "სიღნაღი",
  "ტყიბული",
  "ფოთი",
  "ქარელი",
  "ქედა",
  "ქობულეთი",
  "ქუთაისი",
  "ყაზბეგი",
  "ყვარელი",
  "შუახევი",
  "ჩოხატაური",
  "ჩხოროწყუ",
  "ცაგერი",
  "წალენჯიხა",
  "წალკა",
  "წყალტუბო",
  "ჭიათურა",
  "ხარაგაული",
  "ხაშური",
  "ხელვაჩაური",
  "ხობი",
  "ხონი",
  "ხულო",
] as const;

export const GEORGIAN_CITY_OPTIONS = GEORGIAN_CITIES.map((c) => ({
  value: c,
  label: c,
}));
