import { merge } from "./_i18n-merge.mjs";

merge({
  ka: {
    AuthLogin: {
      tagline: "პრემიუმ ეკოსისტემა",
      title: "შესვლა / რეგისტრაცია",
      emailTab: "ელ. ფოსტა",
      phoneTab: "ტელეფონი",
      emailLabel: "ელ. ფოსტა",
      passwordLabel: "პაროლი",
      confirmPasswordLabel: "პაროლის დადასტურება",
      signIn: "შესვლა",
      register: "რეგისტრაცია",
      noAccount: "არ გაქვთ ანგარიში? რეგისტრაცია",
      haveAccount: "უკვე გაქვთ ანგარიში? შესვლა",
      continueWithGoogle: "გაგრძელება Google-ით",
      continueWithFacebook: "გაგრძელება Facebook-ით",
      or: "ან",
      phoneLabel: "ტელეფონის ნომერი",
      getSmsCode: "SMS კოდის მიღება",
      otpLabel: "ერთჯერადი კოდი",
      verify: "დადასტურება",
      changeNumber: "ნომრის შეცვლა",
      confirmationLinkSent:
        "დადასტურების ბმული გამოგზავნილია თქვენს ელ. ფოსტაზე.",
      agreePrefix: "შესვლით თქვენ ეთანხმებით",
      termsOfService: "მომსახურების პირობებს",
      and: "და",
      privacyPolicy: "კონფიდენციალურობის პოლიტიკას",
      errors: {
        invalidPhone: "გთხოვთ შეიყვანოთ სწორი ტელეფონის ნომერი",
        invalidOtp: "გთხოვთ შეიყვანოთ 6-ციფრიანი კოდი",
        wrongCode: "არასწორი კოდი. სცადეთ თავიდან.",
        fillAllFields: "გთხოვთ შეავსოთ ყველა ველი",
        wrongCredentials: "არასწორი ელ. ფოსტა ან პაროლი",
        passwordTooShort: "პაროლი მინიმუმ 6 სიმბოლო",
        passwordsMismatch: "პაროლები არ ემთხვევა",
        emailTaken: "ეს ელ. ფოსტა უკვე რეგისტრირებულია.",
        generic: "შეცდომა. სცადეთ თავიდან.",
        error: "შეცდომა.",
      },
    },
    AuthRegister: {
      createProfile: "პროფილის შექმნა",
      chooseRole: "აირჩიეთ როლი",
      createProfileHint: "შეავსეთ თქვენი პროფილის ინფორმაცია",
      chooseRoleHint: "რა როლით გსურთ პლატფორმის გამოყენება?",
      avatarAlt: "ავატარი",
      uploadPhoto: "ფოტოს ატვირთვა",
      nameLabel: "სახელი",
      namePlaceholder: "თქვენი სახელი",
      bioLabel: "ბიო",
      bioPlaceholder: "მოკლე აღწერა...",
      next: "შემდეგი",
      back: "უკან",
      finish: "დასრულება",
      roles: {
        guest: "სტუმარი",
        renter: "გამქირავებელი",
        seller: "გამყიდველი",
        cleaner: "დამლაგებელი",
        food: "კვება",
        entertainment: "გართობა",
        transport: "ტრანსპორტი",
        employment: "დასაქმება",
        handyman: "ხელოსანი",
      },
      errors: {
        enterName: "გთხოვთ შეიყვანოთ სახელი",
        roleUpdateFailed: "როლის განახლება ვერ მოხერხდა. სცადეთ თავიდან.",
        generic: "შეცდომა. სცადეთ თავიდან.",
      },
    },
  },
  en: {
    AuthLogin: {
      tagline: "Premium ecosystem",
      title: "Sign in / Register",
      emailTab: "Email",
      phoneTab: "Phone",
      emailLabel: "Email",
      passwordLabel: "Password",
      confirmPasswordLabel: "Confirm password",
      signIn: "Sign in",
      register: "Register",
      noAccount: "Don't have an account? Register",
      haveAccount: "Already have an account? Sign in",
      continueWithGoogle: "Continue with Google",
      continueWithFacebook: "Continue with Facebook",
      or: "or",
      phoneLabel: "Phone number",
      getSmsCode: "Get SMS code",
      otpLabel: "One-time code",
      verify: "Verify",
      changeNumber: "Change number",
      confirmationLinkSent: "A confirmation link has been sent to your email.",
      agreePrefix: "By signing in you agree to the",
      termsOfService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      errors: {
        invalidPhone: "Please enter a valid phone number",
        invalidOtp: "Please enter the 6-digit code",
        wrongCode: "Wrong code. Try again.",
        fillAllFields: "Please fill in all fields",
        wrongCredentials: "Wrong email or password",
        passwordTooShort: "Password must be at least 6 characters",
        passwordsMismatch: "Passwords do not match",
        emailTaken: "This email is already registered.",
        generic: "Error. Please try again.",
        error: "Error.",
      },
    },
    AuthRegister: {
      createProfile: "Create profile",
      chooseRole: "Choose a role",
      createProfileHint: "Fill in your profile information",
      chooseRoleHint: "How would you like to use the platform?",
      avatarAlt: "Avatar",
      uploadPhoto: "Upload photo",
      nameLabel: "Name",
      namePlaceholder: "Your name",
      bioLabel: "Bio",
      bioPlaceholder: "Short description...",
      next: "Next",
      back: "Back",
      finish: "Finish",
      roles: {
        guest: "Guest",
        renter: "Landlord",
        seller: "Seller",
        cleaner: "Cleaner",
        food: "Food",
        entertainment: "Entertainment",
        transport: "Transport",
        employment: "Employment",
        handyman: "Handyman",
      },
      errors: {
        enterName: "Please enter your name",
        roleUpdateFailed: "Failed to update the role. Try again.",
        generic: "Error. Please try again.",
      },
    },
  },
  ru: {
    AuthLogin: {
      tagline: "Премиум-экосистема",
      title: "Вход / Регистрация",
      emailTab: "Эл. почта",
      phoneTab: "Телефон",
      emailLabel: "Эл. почта",
      passwordLabel: "Пароль",
      confirmPasswordLabel: "Подтверждение пароля",
      signIn: "Войти",
      register: "Регистрация",
      noAccount: "Нет аккаунта? Зарегистрируйтесь",
      haveAccount: "Уже есть аккаунт? Войти",
      continueWithGoogle: "Продолжить с Google",
      continueWithFacebook: "Продолжить с Facebook",
      or: "или",
      phoneLabel: "Номер телефона",
      getSmsCode: "Получить SMS-код",
      otpLabel: "Одноразовый код",
      verify: "Подтвердить",
      changeNumber: "Изменить номер",
      confirmationLinkSent:
        "Ссылка для подтверждения отправлена на вашу почту.",
      agreePrefix: "Входя, вы соглашаетесь с",
      termsOfService: "условиями обслуживания",
      and: "и",
      privacyPolicy: "политикой конфиденциальности",
      errors: {
        invalidPhone: "Пожалуйста, введите корректный номер телефона",
        invalidOtp: "Пожалуйста, введите 6-значный код",
        wrongCode: "Неверный код. Попробуйте снова.",
        fillAllFields: "Пожалуйста, заполните все поля",
        wrongCredentials: "Неверная почта или пароль",
        passwordTooShort: "Пароль — минимум 6 символов",
        passwordsMismatch: "Пароли не совпадают",
        emailTaken: "Эта почта уже зарегистрирована.",
        generic: "Ошибка. Попробуйте снова.",
        error: "Ошибка.",
      },
    },
    AuthRegister: {
      createProfile: "Создание профиля",
      chooseRole: "Выберите роль",
      createProfileHint: "Заполните информацию профиля",
      chooseRoleHint: "В какой роли вы хотите использовать платформу?",
      avatarAlt: "Аватар",
      uploadPhoto: "Загрузить фото",
      nameLabel: "Имя",
      namePlaceholder: "Ваше имя",
      bioLabel: "О себе",
      bioPlaceholder: "Краткое описание...",
      next: "Далее",
      back: "Назад",
      finish: "Завершить",
      roles: {
        guest: "Гость",
        renter: "Арендодатель",
        seller: "Продавец",
        cleaner: "Уборщик",
        food: "Еда",
        entertainment: "Развлечения",
        transport: "Транспорт",
        employment: "Работа",
        handyman: "Мастер",
      },
      errors: {
        enterName: "Пожалуйста, введите имя",
        roleUpdateFailed: "Не удалось обновить роль. Попробуйте снова.",
        generic: "Ошибка. Попробуйте снова.",
      },
    },
  },
});
