import { merge } from "./_i18n-merge.mjs";

merge({
  ka: {
    DateRangeFilter: {
      presets: {
        lastWeek: "ბოლო კვირა",
        last30: "ბოლო 30 დღე",
        thisMonth: "ამ თვეში",
      },
      byMonth: "თვის მიხედვით",
      prevYear: "წინა წელი",
      nextYear: "შემდეგი წელი",
      customPeriod: "მორგებული პერიოდი",
      months: {
        january: "იანვარი",
        february: "თებერვალი",
        march: "მარტი",
        april: "აპრილი",
        may: "მაისი",
        june: "ივნისი",
        july: "ივლისი",
        august: "აგვისტო",
        september: "სექტემბერი",
        october: "ოქტომბერი",
        november: "ნოემბერი",
        december: "დეკემბერი",
      },
    },
    ListingScopeSelect: {
      allListings: "ყველა ობიექტი",
      selectedCount: "{count} ობიექტი არჩეული",
      searchPlaceholder: "ძებნა...",
    },
    ListingActions: {
      view: "ნახვა",
      edit: "რედაქტირება",
      promote: "განცხადების დაწინაურება:",
      discount: "ფასდაკლება",
    },
    GuestDashboard: {
      welcome: "გამარჯობა, {name}, მზად ხარ დასვენებისთვის? 🏔️",
      defaultName: "სტუმარი",
      subtitle:
        "აქ მოელის ახალი თავგადასავალი — ჯავშნები, შეთავაზებები და სერვისები ერთ სივრცეში.",
      newRequest: "ახალი მოთხოვნა",
      offersTitleNew: "თქვენ გაქვთ {count} ახალი შეთავაზება!",
      offersTitleEmpty: "გაგზავნე მოთხოვნა და მიიღე საუკეთესო შეთავაზებები",
      offersDescNew:
        "მფლობელებმა გამოგზავნეს პერსონალური შეთავაზებები — შეადარე და აირჩიე საუკეთესო.",
      offersDescEmpty:
        "დააფიქსირე სასურველი პირობები და მფლობელები პირდაპირ გამოგიგზავნიან შეთავაზებებს.",
      viewOffers: "შეთავაზებების ნახვა",
      sendRequest: "მოთხოვნის გაგზავნა",
      pendingReviews: "შეფასების მოლოდინში ({count})",
      pendingReviewsHint:
        "დასრულებული დარჩენების შესახებ მიმოხილვის დატოვება დაგვეხმარება სხვა სტუმრებს.",
      review: "შეფასება",
      recentTitle: "ბოლოს ნანახი განცხადებები",
      recentSubtitle: "გააგრძელე სადაც გაჩერდი.",
      viewAll: "ყველას ნახვა",
      views: "{count} ნახვა",
      perNight: "/ღამე",
    },
    GuestBookings: {
      title: "მიღებული შეთავაზებები",
      subtitle:
        "მფლობელების პერსონალური შეთავაზებები თქვენი მოთხოვნის მიხედვით.",
      newRequest: "ახალი მოთხოვნა",
      tabAll: "ყველა ({count})",
      tabNew: "ახალი ({count})",
      emptyTitle: "ჯერ არ გაქვთ შეთავაზებები",
      emptyDesc: "გაგზავნეთ მოთხოვნა და მფლობელები დაგიკავშირდებიან.",
      defaultOwner: "მფლობელი",
      ownerRole: "სახლის მფლობელი",
      badgeNew: "ახალი",
      badgeDeclined: "უარყოფილი",
      offeredPrice: "შემოთავაზებული ფასი",
      perNight: "/ღამე",
      cheaper: "✓ იაფი (ლისტინგი: {price}₾)",
      decline: "უარყოფა",
      viewDetails: "დეტალურად ნახვა",
    },
    GuestProfile: {
      title: "პროფილის პარამეტრები",
      subtitle:
        "მართეთ თქვენი პერსონალური მონაცემები და საკონტაქტო ინფორმაცია.",
      avatarTitle: "პროფილის ფოტო",
      avatarHint: "ატვირთეთ ფოტო (JPG, PNG). მაქს. ზომა 2MB.",
      uploadPhoto: "ატვირთე ფოტო",
      firstName: "სახელი",
      lastName: "გვარი",
      phone: "ტელეფონის ნომერი",
      email: "ელ. ფოსტა (Gmail)",
      cancel: "გაუქმება",
      saving: "შენახვა...",
      saved: "შენახულია",
      saveChanges: "ცვლილებების შენახვა",
      defaultInitial: "ს",
      errors: {
        fileTooLarge: "ფაილი არ უნდა აღემატებოდეს 2MB-ს",
        invalidFormat: "მხოლოდ JPG და PNG ფორმატია დაშვებული",
        uploadFailed: "ფოტოს ატვირთვა ვერ მოხერხდა",
      },
    },
    GuestReviews: {
      title: "კომუნიკაციის ისტორია",
      subtitle: "ბოლო სერვისები და შეფასებები.",
      recentCalls: "ბოლო ზარები",
      myReviews: "ჩემი შეფასებები",
      noCalls: "ზარები არ არის",
      noReviews: "შეფასებები არ გაქვთ",
      defaultProperty: "ობიექტი",
      undated: "დაუთარიღებელი",
      calledToday: "დარეკეთ დღეს, {time}",
      calledYesterday: "დარეკეთ გუშინ, {time}",
      calledDaysAgo: "დარეკეთ {days} დღის წინ",
      calledOn: "დარეკეთ {date}",
    },
    GuestFavorites: {
      title: "ჩემი რჩეულები",
      subtitle:
        "აქ ინახება ყველა სახის უძრავი ქონება და საინტერესო წინადადება.",
      emptyTitle: "ჯერ არ გაქვთ რჩეული",
      emptyDesc: "დაამატეთ ქონება ან სერვისი გულის ხატულით ნახვის გვერდიდან.",
      browseListings: "ნახე განცხადებები",
      sectionProperties: "აპარტამენტები და კოტეჯები",
      sectionServices: "ტრანსპორტი და გართობა",
      viewAll: "ყველას ნახვა",
      removeFromFavorites: "წაშლა რჩეულებიდან",
      view: "ნახვა",
      perNight: "/ღამე",
    },
    SellerDashboard: {
      kpiTitle: "მთავარი მაჩვენებლები",
      metrics: {
        newInterest: "ახალი დაინტერესება",
        newLeads: "ახალი ლიდი (კლიენტი)",
        sold: "გაყიდული ობიექტი",
        favorites: "რჩეულში დამატება",
        views: "ობიექტის ნახვები",
        contactReach: "კონტაქტამდე მისვლა",
        smsViews: "ნომრის / SMS ნახვა",
      },
      badgeTotal: "სულ",
      listingsTitle: "ჩემი განცხადებები",
      activeCount: "{count} აქტიური განცხადება",
      add: "დამატება",
      emptyTitle: "გასაყიდი ობიექტები ჯერ არ გაქვთ",
      emptyDesc: "დაამატეთ პირველი ობიექტი და დაიწყეთ გაყიდვა",
      addProperty: "დაამატეთ ობიექტი",
      forSale: "გაყიდვა",
      statuses: {
        active: "აქტიური",
        blocked: "დაბლოკილი",
        pending: "მოლოდინში",
        draft: "დრაფტი",
      },
    },
    SellerListings: {
      title: "ობიექტები / პროექტები",
      subtitle: "მართეთ თქვენი პორთფოლიო, სტატუსები და განახლებები.",
      addProperty: "ობიექტის დამატება",
      searchPlaceholder: "ობიექტის ძებნა...",
      notFound: "ობიექტები ვერ მოიძებნა",
      constructionStatus: {
        under_construction: "მშენებარე",
        completed: "დასრულებული",
        ready: "მზა",
      },
      multiUnitProject: "მრავალბინიანი პროექტი",
      developerProject: "{developer} • მრავალბინიანი პროექტი",
      salesProgress: "გაყიდვების პროგრესი",
      legend: {
        sold: "გაყიდული",
        reserved: "ჯავშანი",
        available: "თავისუფალი",
      },
      readiness: "მზადყოფნა • {year}",
      completed: "ობიექტი დასრულებულია",
      lastUpdate: "ბოლო განახლება",
      updateProgress: "პროგრესის / სტატუსის განახლება",
    },
  },
  en: {
    DateRangeFilter: {
      presets: {
        lastWeek: "Last week",
        last30: "Last 30 days",
        thisMonth: "This month",
      },
      byMonth: "By month",
      prevYear: "Previous year",
      nextYear: "Next year",
      customPeriod: "Custom period",
      months: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
    },
    ListingScopeSelect: {
      allListings: "All listings",
      selectedCount: "{count} listings selected",
      searchPlaceholder: "Search...",
    },
    ListingActions: {
      view: "View",
      edit: "Edit",
      promote: "Promote listing:",
      discount: "Discount",
    },
    GuestDashboard: {
      welcome: "Hello, {name}, ready for a getaway? 🏔️",
      defaultName: "Guest",
      subtitle:
        "Your next adventure awaits — bookings, offers, and services in one place.",
      newRequest: "New request",
      offersTitleNew: "You have {count} new offers!",
      offersTitleEmpty: "Send a request and get the best offers",
      offersDescNew:
        "Owners sent you personal offers — compare them and pick the best one.",
      offersDescEmpty:
        "Set your preferences and owners will send you offers directly.",
      viewOffers: "View offers",
      sendRequest: "Send request",
      pendingReviews: "Pending reviews ({count})",
      pendingReviewsHint:
        "Leaving a review after completed stays helps other guests.",
      review: "Review",
      recentTitle: "Recently viewed listings",
      recentSubtitle: "Pick up where you left off.",
      viewAll: "View all",
      views: "{count} views",
      perNight: "/night",
    },
    GuestBookings: {
      title: "Received offers",
      subtitle: "Personal offers from owners based on your request.",
      newRequest: "New request",
      tabAll: "All ({count})",
      tabNew: "New ({count})",
      emptyTitle: "No offers yet",
      emptyDesc: "Send a request and owners will reach out to you.",
      defaultOwner: "Owner",
      ownerRole: "Property owner",
      badgeNew: "New",
      badgeDeclined: "Declined",
      offeredPrice: "Offered price",
      perNight: "/night",
      cheaper: "✓ Cheaper (listing: {price}₾)",
      decline: "Decline",
      viewDetails: "View details",
    },
    GuestProfile: {
      title: "Profile settings",
      subtitle: "Manage your personal details and contact information.",
      avatarTitle: "Profile photo",
      avatarHint: "Upload a photo (JPG, PNG). Max size 2MB.",
      uploadPhoto: "Upload photo",
      firstName: "First name",
      lastName: "Last name",
      phone: "Phone number",
      email: "Email (Gmail)",
      cancel: "Cancel",
      saving: "Saving...",
      saved: "Saved",
      saveChanges: "Save changes",
      defaultInitial: "G",
      errors: {
        fileTooLarge: "File must not exceed 2MB",
        invalidFormat: "Only JPG and PNG formats are allowed",
        uploadFailed: "Failed to upload photo",
      },
    },
    GuestReviews: {
      title: "Communication history",
      subtitle: "Recent services and reviews.",
      recentCalls: "Recent calls",
      myReviews: "My reviews",
      noCalls: "No calls yet",
      noReviews: "No reviews yet",
      defaultProperty: "Property",
      undated: "Undated",
      calledToday: "Called today, {time}",
      calledYesterday: "Called yesterday, {time}",
      calledDaysAgo: "Called {days} days ago",
      calledOn: "Called {date}",
    },
    GuestFavorites: {
      title: "My favorites",
      subtitle: "All saved properties and interesting offers in one place.",
      emptyTitle: "No favorites yet",
      emptyDesc:
        "Add a property or service using the heart icon on listing pages.",
      browseListings: "Browse listings",
      sectionProperties: "Apartments and cottages",
      sectionServices: "Transport and entertainment",
      viewAll: "View all",
      removeFromFavorites: "Remove from favorites",
      view: "View",
      perNight: "/night",
    },
    SellerDashboard: {
      kpiTitle: "Key metrics",
      metrics: {
        newInterest: "New interest",
        newLeads: "New leads (clients)",
        sold: "Properties sold",
        favorites: "Added to favorites",
        views: "Listing views",
        contactReach: "Contact reach",
        smsViews: "Phone / SMS views",
      },
      badgeTotal: "Total",
      listingsTitle: "My listings",
      activeCount: "{count} active listings",
      add: "Add",
      emptyTitle: "No properties for sale yet",
      emptyDesc: "Add your first property and start selling",
      addProperty: "Add property",
      forSale: "For sale",
      statuses: {
        active: "Active",
        blocked: "Blocked",
        pending: "Pending",
        draft: "Draft",
      },
    },
    SellerListings: {
      title: "Properties / projects",
      subtitle: "Manage your portfolio, statuses, and updates.",
      addProperty: "Add property",
      searchPlaceholder: "Search properties...",
      notFound: "No properties found",
      constructionStatus: {
        under_construction: "Under construction",
        completed: "Completed",
        ready: "Ready",
      },
      multiUnitProject: "Multi-unit project",
      developerProject: "{developer} • Multi-unit project",
      salesProgress: "Sales progress",
      legend: {
        sold: "Sold",
        reserved: "Reserved",
        available: "Available",
      },
      readiness: "Completion • {year}",
      completed: "Property completed",
      lastUpdate: "Latest update",
      updateProgress: "Update progress / status",
    },
  },
  ru: {
    DateRangeFilter: {
      presets: {
        lastWeek: "Последняя неделя",
        last30: "Последние 30 дней",
        thisMonth: "В этом месяце",
      },
      byMonth: "По месяцам",
      prevYear: "Предыдущий год",
      nextYear: "Следующий год",
      customPeriod: "Произвольный период",
      months: {
        january: "Январь",
        february: "Февраль",
        march: "Март",
        april: "Апрель",
        may: "Май",
        june: "Июнь",
        july: "Июль",
        august: "Август",
        september: "Сентябрь",
        october: "Октябрь",
        november: "Ноябрь",
        december: "Декабрь",
      },
    },
    ListingScopeSelect: {
      allListings: "Все объекты",
      selectedCount: "Выбрано объектов: {count}",
      searchPlaceholder: "Поиск...",
    },
    ListingActions: {
      view: "Смотреть",
      edit: "Редактировать",
      promote: "Продвижение объявления:",
      discount: "Скидка",
    },
    GuestDashboard: {
      welcome: "Здравствуйте, {name}, готовы к отдыху? 🏔️",
      defaultName: "Гость",
      subtitle:
        "Здесь вас ждёт новое приключение — бронирования, предложения и услуги в одном месте.",
      newRequest: "Новый запрос",
      offersTitleNew: "У вас {count} новых предложений!",
      offersTitleEmpty: "Отправьте запрос и получите лучшие предложения",
      offersDescNew:
        "Владельцы отправили персональные предложения — сравните и выберите лучшее.",
      offersDescEmpty:
        "Укажите желаемые условия, и владельцы отправят вам предложения напрямую.",
      viewOffers: "Смотреть предложения",
      sendRequest: "Отправить запрос",
      pendingReviews: "Ожидают отзыва ({count})",
      pendingReviewsHint:
        "Отзывы после завершённых поездок помогают другим гостям.",
      review: "Оценить",
      recentTitle: "Недавно просмотренные объявления",
      recentSubtitle: "Продолжите с того места, где остановились.",
      viewAll: "Смотреть все",
      views: "{count} просмотров",
      perNight: "/ночь",
    },
    GuestBookings: {
      title: "Полученные предложения",
      subtitle: "Персональные предложения от владельцев по вашему запросу.",
      newRequest: "Новый запрос",
      tabAll: "Все ({count})",
      tabNew: "Новые ({count})",
      emptyTitle: "Пока нет предложений",
      emptyDesc: "Отправьте запрос, и владельцы свяжутся с вами.",
      defaultOwner: "Владелец",
      ownerRole: "Владелец жилья",
      badgeNew: "Новое",
      badgeDeclined: "Отклонено",
      offeredPrice: "Предложенная цена",
      perNight: "/ночь",
      cheaper: "✓ Дешевле (в объявлении: {price}₾)",
      decline: "Отклонить",
      viewDetails: "Подробнее",
    },
    GuestProfile: {
      title: "Настройки профиля",
      subtitle: "Управляйте личными данными и контактной информацией.",
      avatarTitle: "Фото профиля",
      avatarHint: "Загрузите фото (JPG, PNG). Макс. размер 2MB.",
      uploadPhoto: "Загрузить фото",
      firstName: "Имя",
      lastName: "Фамилия",
      phone: "Номер телефона",
      email: "Email (Gmail)",
      cancel: "Отмена",
      saving: "Сохранение...",
      saved: "Сохранено",
      saveChanges: "Сохранить изменения",
      defaultInitial: "Г",
      errors: {
        fileTooLarge: "Файл не должен превышать 2MB",
        invalidFormat: "Допустимы только форматы JPG и PNG",
        uploadFailed: "Не удалось загрузить фото",
      },
    },
    GuestReviews: {
      title: "История общения",
      subtitle: "Последние услуги и отзывы.",
      recentCalls: "Последние звонки",
      myReviews: "Мои отзывы",
      noCalls: "Звонков пока нет",
      noReviews: "Отзывов пока нет",
      defaultProperty: "Объект",
      undated: "Без даты",
      calledToday: "Звонок сегодня, {time}",
      calledYesterday: "Звонок вчера, {time}",
      calledDaysAgo: "Звонок {days} дн. назад",
      calledOn: "Звонок {date}",
    },
    GuestFavorites: {
      title: "Избранное",
      subtitle:
        "Здесь хранятся все виды недвижимости и интересные предложения.",
      emptyTitle: "Пока нет избранного",
      emptyDesc:
        "Добавьте объект или услугу через значок сердца на странице объявления.",
      browseListings: "Смотреть объявления",
      sectionProperties: "Апартаменты и коттеджи",
      sectionServices: "Транспорт и развлечения",
      viewAll: "Смотреть все",
      removeFromFavorites: "Удалить из избранного",
      view: "Смотреть",
      perNight: "/ночь",
    },
    SellerDashboard: {
      kpiTitle: "Ключевые показатели",
      metrics: {
        newInterest: "Новый интерес",
        newLeads: "Новые лиды (клиенты)",
        sold: "Проданные объекты",
        favorites: "Добавления в избранное",
        views: "Просмотры объекта",
        contactReach: "Доходимость до контакта",
        smsViews: "Просмотры номера / SMS",
      },
      badgeTotal: "Всего",
      listingsTitle: "Мои объявления",
      activeCount: "{count} активных объявлений",
      add: "Добавить",
      emptyTitle: "Объектов на продажу пока нет",
      emptyDesc: "Добавьте первый объект и начните продажу",
      addProperty: "Добавить объект",
      forSale: "Продажа",
      statuses: {
        active: "Активно",
        blocked: "Заблокировано",
        pending: "На модерации",
        draft: "Черновик",
      },
    },
    SellerListings: {
      title: "Объекты / проекты",
      subtitle: "Управляйте портфелем, статусами и обновлениями.",
      addProperty: "Добавить объект",
      searchPlaceholder: "Поиск объектов...",
      notFound: "Объекты не найдены",
      constructionStatus: {
        under_construction: "Строится",
        completed: "Завершён",
        ready: "Готов",
      },
      multiUnitProject: "Многоквартирный проект",
      developerProject: "{developer} • Многоквартирный проект",
      salesProgress: "Прогресс продаж",
      legend: {
        sold: "Продано",
        reserved: "Бронь",
        available: "Свободно",
      },
      readiness: "Готовность • {year}",
      completed: "Объект завершён",
      lastUpdate: "Последнее обновление",
      updateProgress: "Обновить прогресс / статус",
    },
  },
});
