import { merge } from "./_i18n-merge.mjs";

merge({
  ka: {
    ListingOptions: {
      other: "სხვა",
      servicePriceUnits: { hour: "საათი" },
      cleaningTypes: { standard: "სტანდარტული", general: "გენერალური" },
      propertyTypes: {
        apartment: "აპარტამენტი",
        studio: "სტუდიო",
        cottage: "კოტეჯი",
        hotel: "სასტუმრო ოთახი",
        villa: "ვილა",
      },
      serviceCategories: {
        food: "კვება",
        transport: "ტრანსპორტი",
        entertainment: "გართობა",
        employment: "სამუშაო",
        handyman: "ხელოსანი",
        cleaning: "დასუფთავება",
      },
      listingStatuses: {
        active: "აქტიური",
        blocked: "დაბლოკილი",
        pending: "მოლოდინში",
        draft: "შავი ვარიანტი",
      },
      amenityGroupLabels: {
        winter: "ზამთრის ინფრასტრუქტურა",
        comfort: "საბაზისო კომფორტი",
        kitchen: "სამზარეულო და საყოფაცხოვრებო",
        outdoor: "აივანი / გარე სივრცე",
      },
      amenities: {
        ski_in_out: "Ski-in / Ski-out",
        ski_storage: "თხილამურების სათავსო",
        backup_generator: "სარეზერვო გენერატორი",
        fireplace: "ბუხარი",
        parking: "პარკინგი",
        wifi: "უფასო Wi-Fi",
        central_heating: "ცენტრალური გათბობა",
        tv: "ტელევიზორი",
        washing_machine: "სარეცხი მანქანა",
        dishwasher: "ჭურჭლის სარეცხი მანქანა",
        full_kitchen: "სრულად აღჭურვილი სამზარეულო",
        coffee_maker: "ყავის აპარატი",
        no_balcony: "არ აქვს",
        french_balcony: "ფრანგული აივანი",
        standard_balcony: "სტანდარტული აივანი",
        large_terrace: "დიდი ტერასა",
        yard: "ეზო",
      },
      hostingLangs: {
        ka: "ქართული",
        en: "English",
        ru: "Русский",
        ar: "Arabic",
      },
    },
  },
  en: {
    ListingOptions: {
      other: "Other",
      servicePriceUnits: { hour: "hour" },
      cleaningTypes: { standard: "Standard", general: "Deep cleaning" },
      propertyTypes: {
        apartment: "Apartment",
        studio: "Studio",
        cottage: "Cottage",
        hotel: "Hotel room",
        villa: "Villa",
      },
      serviceCategories: {
        food: "Food",
        transport: "Transport",
        entertainment: "Entertainment",
        employment: "Jobs",
        handyman: "Handyman",
        cleaning: "Cleaning",
      },
      listingStatuses: {
        active: "Active",
        blocked: "Blocked",
        pending: "Pending",
        draft: "Draft",
      },
      amenityGroupLabels: {
        winter: "Winter infrastructure",
        comfort: "Basic comfort",
        kitchen: "Kitchen & household",
        outdoor: "Balcony / outdoor space",
      },
      amenities: {
        ski_in_out: "Ski-in / Ski-out",
        ski_storage: "Ski storage",
        backup_generator: "Backup generator",
        fireplace: "Fireplace",
        parking: "Parking",
        wifi: "Free Wi-Fi",
        central_heating: "Central heating",
        tv: "TV",
        washing_machine: "Washing machine",
        dishwasher: "Dishwasher",
        full_kitchen: "Fully equipped kitchen",
        coffee_maker: "Coffee maker",
        no_balcony: "None",
        french_balcony: "French balcony",
        standard_balcony: "Standard balcony",
        large_terrace: "Large terrace",
        yard: "Yard",
      },
      hostingLangs: {
        ka: "Georgian",
        en: "English",
        ru: "Russian",
        ar: "Arabic",
      },
    },
  },
  ru: {
    ListingOptions: {
      other: "Другое",
      servicePriceUnits: { hour: "час" },
      cleaningTypes: { standard: "Стандартная", general: "Генеральная" },
      propertyTypes: {
        apartment: "Апартаменты",
        studio: "Студия",
        cottage: "Коттедж",
        hotel: "Гостиничный номер",
        villa: "Вилла",
      },
      serviceCategories: {
        food: "Питание",
        transport: "Транспорт",
        entertainment: "Развлечения",
        employment: "Работа",
        handyman: "Мастер",
        cleaning: "Уборка",
      },
      listingStatuses: {
        active: "Активно",
        blocked: "Заблокировано",
        pending: "На рассмотрении",
        draft: "Черновик",
      },
      amenityGroupLabels: {
        winter: "Зимняя инфраструктура",
        comfort: "Базовый комфорт",
        kitchen: "Кухня и быт",
        outdoor: "Балкон / открытое пространство",
      },
      amenities: {
        ski_in_out: "Ski-in / Ski-out",
        ski_storage: "Хранение лыж",
        backup_generator: "Резервный генератор",
        fireplace: "Камин",
        parking: "Парковка",
        wifi: "Бесплатный Wi-Fi",
        central_heating: "Центральное отопление",
        tv: "Телевизор",
        washing_machine: "Стиральная машина",
        dishwasher: "Посудомоечная машина",
        full_kitchen: "Полностью оборудованная кухня",
        coffee_maker: "Кофемашина",
        no_balcony: "Нет",
        french_balcony: "Французский балкон",
        standard_balcony: "Стандартный балкон",
        large_terrace: "Большая терраса",
        yard: "Двор",
      },
      hostingLangs: {
        ka: "Грузинский",
        en: "Английский",
        ru: "Русский",
        ar: "Арабский",
      },
    },
  },
});
