import { merge } from "./_i18n-merge.mjs";

merge({
  ka: {
    CreateHub: {
      title: "განცხადების დამატება",
      subtitle: "აირჩიეთ კატეგორია",
      categories: {
        rental: "ქირაობა",
        sale: "ყიდვა / გაყიდვა",
        employment: "დასაქმება",
        service: "სერვისები",
        transport: "ტრანსპორტი",
        food: "კვება",
        entertainment: "გართობა",
      },
    },
    Wizard: { step: "ნაბიჯი" },
    CreateHeader: {
      addListing: "განცხადების დამატება",
      balance: "ბალანსი",
      cabinet: "კაბინეტი",
      signIn: "შესვლა",
    },
    PhotoUploader: {
      skippedInvalid: "{count} ფაილი გამოტოვდა — მხოლოდ JPG, PNG, WEBP",
      skippedByLimit: "{count} ფაილი გამოტოვდა — მაქს. {max} ფოტო",
      uploadPhotos: "ფოტოების ატვირთვა",
      dropHereOrClick: "ჩააგდეთ აქ ან დააწკაპუნეთ",
      maxPhotos: "მაქს. {max} ფოტო",
      uploadPhotosAlt: "ატვირთეთ ფოტოები",
      dropHereOrClickSelect: "ჩააგდეთ ან აირჩიეთ ფოტოები",
      photoCount: "{count} / {max} ფოტო",
    },
    MediaUploader: {
      defaultLabel: "მედია (სურათი ან ვიდეო)",
      defaultHelper: "JPG / PNG / WEBP მაქს. 5MB ან MP4 / WebM მაქს. 50MB",
      invalidFileType: "არასწორი ფაილის ტიპი: {type}",
      posterMustBeImage: "პოსტერი უნდა იყოს სურათი",
      fileTooLarge: "ფაილი ძალიან დიდია. მაქს. {mb}MB",
      uploadFailed: "ატვირთვა ვერ მოხერხდა",
      fileUploadFailed: "ფაილის ატვირთვა ვერ მოხერხდა",
      error: "შეცდომა",
      delete: "წაშლა",
      uploading: "იტვირთება…",
      chooseFile: "ფაილის არჩევა",
      videoPoster: "ვიდეოს პოსტერი",
      posterImageOnly: "აქცეპტდება მხოლოდ სურათი",
      videoPosterOptional: "ვიდეოს პოსტერი (სურვილისამებრ)",
      posterPreviewHint: "პრევიუ, სანამ ვიდეო ჩაიტვირთება",
      change: "შეცვლა",
      choose: "არჩევა",
    },
    BulkActionBar: {
      quickSelect: "სწრაფი მონიშვნა",
      allAvailable: "მთელი თვე ხელმისაწვდომი",
      allBlocked: "მთელი თვე დაკავებული",
      weekdaysOnly: "მხოლოდ სამუშაო დღეები",
      weekendsOnly: "მხოლოდ პარ.–კვ.",
      blockNext7: "მომდევნო 7 დღის დაკავება",
    },
    AvailabilityWizard: {
      introTitle: "მონიშნე დღეები და დააყენე ფასი მომდევნო 30 დღისთვის.",
      introBody:
        "დააწექი ან გადაიტანე მაუსი დღეების ასარჩევად, შემდეგ დააყენე ფასი ან გათიშე ისინი. ნაგულისხმევად ყველა დღე ხელმისაწვდომია ძირითადი ფასით — {orange} ფასი ნიშნავს, რომ ის შეცვლილია.",
      orangeHighlight: "ნარინჯისფერი",
      availableCount: "{count} ხელმისაწვდომი",
      blockedCount: "{count} დაკავებული",
      daysConfirmed: "{total} / 30 დღე დადასტურებულია",
      cancelSelection: "გაუქმება",
      selectedMixed: "{available} ხელმისაწვდომი • {blocked} დაკავებული",
      selectedAvailable: "{count} დღე არჩეული",
      selectedBlocked: "{count} დაკავებული არჩეული",
      avgPrice: "საშუალო ფასი: {price}₾",
      unblock: "ჩართვა ({count})",
      block: "გათიშვა ({count})",
      newPricePlaceholder: "ახალი ფასი",
      applyPrice: "გადატარება",
      resetPriceTitle: "ფასი ნაგულისხმევზე დაბრუნება",
      resetPrice: "ნაგულისხმევზე",
      footerHint:
        "შეგიძლიათ მოგვიანებით განაახლოთ კალენდარი და ფასები თქვენი დაშბორდიდან.",
      booked: "დაჯავშნა",
      blockedSelect: "დაკავებული, დააწექი რომ აირჩიო",
      availablePrice: "ხელმისაწვდომი, {price}₾",
    },
    CreateShared: {
      listingNotFound: "განცხადება ვერ მოიძებნა",
      genericError: "შეცდომა. სცადეთ თავიდან.",
      save: "შენახვა",
      publishListing: "განცხადების გამოქვეყნება",
      loading: "იტვირთება...",
      basicInfo: "ძირითადი ინფორმაცია",
      contactInfo: "საკონტაქტო ინფორმაცია",
      description: "აღწერა",
      phoneNumber: "ტელეფონის ნომერი",
      whatsappNumber: "WhatsApp ნომერი",
      whatsappOptional: "WhatsApp სურვილისამებრ",
      optional: "სურვილისამებრ",
      chooseType: "აირჩიეთ ტიპი",
      chooseZone: "აირჩიეთ ზონა",
      choosePrice: "აირჩიეთ ფასი",
      choose: "აირჩიე",
      delete: "წაშლა",
      showOnMap: "რუკაზე ჩვენება",
      pickOnMap: "რუკაზე არჩევა",
      minPhotos: "მინიმუმ {count} ფოტო",
      minPhotosShort: "მინ. {count} ფოტო",
      enterPhone: "მიუთითეთ ტელეფონის ნომერი",
      minPhotosRequired: "მინიმუმ {count} ფოტო აუცილებელია",
      uploadMinOnePhoto: "ატვირთეთ მინიმუმ ერთი ფოტო",
      eg: "მაგ: {value}",
      sqm: "კვ.მ",
      or: "ან",
      onlyUnderConstruction: "მხოლოდ მშენებარეზე",
    },
    ListingOptions: {
      foodAmenities: {
        has_kids_area: "საბავშვო სივრცე",
        has_lounge: "მოწევის ზონა",
        has_delivery: "მიტანის სერვისი",
        has_live_music: "ცოცხალი მუსიკა",
      },
      restaurantTypes: {
        restaurant: "რესტორანი",
        cafe: "კაფე / საკონდიტრო",
        bar: "ბარი / პაბი",
        fast_food: "სწრაფი კვება",
        other: "სხვა",
      },
      cuisineTypes: {
        georgian: "ქართული",
        european: "ევროპული",
        asian: "აზიური",
        mixed: "შერეული",
      },
      transportTypes: {
        minivan: "მინივენი",
        taxi: "ტაქსი",
        microbus: "მიკროავტობუსი",
        other: "სხვა",
      },
      priceUnits: {
        whole_car: "მთლიანი მანქანა",
        on_demand: "გამოძახება",
        per_person: "ერთ კაცზე",
      },
      serviceSpheres: {
        cleaning: "დასუფთავება/დამლაგებელი",
        handymen: "ხელოსნები",
        staff: "მომსახურე პერსონალი",
        tourism: "ტურიზმი",
        sales: "გაყიდვები/ვაჭრობა",
        other: "სხვა",
      },
      coverageZones: {
        all_bakuriani: "მთლიანი ბაკურიანი",
        mitarbi: "მიტარბი",
        tsalgeri: "წალვერი",
      },
      languages: {
        ka: "ქართული",
        en: "ინგლისური",
        ru: "რუსული",
      },
      vehicleColors: {
        white: "თეთრი",
        black: "შავი",
        gray: "ნაცრისფერი",
        silver: "ვერცხლისფერი",
        red: "წითელი",
        blue: "ლურჯი",
        light_blue: "ცისფერი",
        green: "მწვანე",
        yellow: "ყვითელი",
        orange: "ნარინჯისფერი",
        brown: "ყავისფერი",
        gold: "ოქროსფერი",
        other: "სხვა",
      },
      transportFeatures: {
        ac: "კონდიციონერი",
        wifi: "Wi-Fi",
        usb: "USB დამტენი",
        music: "მუსიკა",
        water: "წყალი",
        child_seat: "ბავშვის სავარძელი",
      },
      entertainmentTypes: {
        extreme: "ექსტრემალური",
        sport: "სპორტული",
        kids: "ბავშვებისთვის",
        family: "ოჯახისთვის",
        other: "სხვა",
      },
      entertainmentCategories: {
        inventory_rent: "ინვენტარი",
        horses: "ცხენები",
        buggies: "ბურანები",
        quad_bikes: "კვადროციკლები",
        buggy: "ბაგი",
        other: "სხვა",
      },
      durations: {
        "15min": "15 წუთი",
        "30min": "30 წუთი",
        "1h": "1 საათი",
        "1h+": "1+ საათი",
      },
      ageOptions: {
        any: "ნებისმიერი",
      },
      audienceOptions: {
        all: "ყველასთვის",
        extreme_lovers: "ექსტრემის მოყვარულთა",
      },
      pricePerOptions: {
        "15min": "15 წუთზე",
        "1h": "1 საათზე",
        full_day: "სრულ დღეზე",
      },
      employmentTypes: {
        full_time: "სრული განაკვეთი",
        part_time: "ნახევარი განაკვეთი",
        flexible: "მოქნილი",
      },
      salaryTypes: {
        fixed: "ფიქსირებული",
        fixed_bonus: "ფიქსირებული + ბონუსი/Tips",
        commission: "გამომუშავებით (%)",
        negotiable: "შეთანხმებით",
      },
      experienceOptions: {
        preferred: "სასურველია",
        not_required: "არ არის აუცილებელი",
        one_year: "1 წელი",
        one_plus_year: "1+ წელი",
      },
      accommodationOptions: {
        yes: "კი",
        no: "არა",
        negotiable: "შეთანხმებით",
      },
      mealsOptions: {
        full: "სრული კვება",
        single: "ერთჯერადი კვება",
        not_included: "არ შედის",
      },
      salePropertyTypes: {
        studio: "სტუდიო",
        apartment: "აპარტამენტი",
        cottage: "კოტეჯი",
        villa: "მიწის ნაკვეთი",
        hotel: "სასტუმრო ოთახი",
      },
      constructionStatuses: {
        under_construction: "მშენებარე",
        completed: "ახალი აშენებული/დასრულებული",
      },
    },
    CreateFood: {
      pageTitle: "კვება და რესტორნები",
      sectionDetails: "დეტალები და სერვისები",
      sectionMenuPhotos: "მენიუ და ფოტოები",
      objectTitle: "ობიექტის დასახელება",
      titlePlaceholder: "მაგ: რესტორანი პანორამა",
      restaurantType: "რესტორნის ტიპი",
      cuisineType: "სამზარეულოს ტიპი",
      locationZone: "ლოკაცია (ZONE)",
      exactLocation: "ზუსტი ლოკაცია",
      exactLocationPlaceholder: "მაგ: ცენტრალური პარკის შესასვლელთან",
      descriptionPlaceholder: "დეტალური აღწერა რესტორნის შესახებ...",
      avgCheck: "საშუალო ჩეკი 1 პერსონაზე",
      operatingHours: "სამუშაო საათები",
      hoursPlaceholder: "მაგ: 10:00 - 20:00",
      extraDetails: "დამატებითი დეტალები",
      menuOptional: "მენიუ (არასავალდებულო)",
      uploadMenu: "მენიუს ატვირთვა",
      pdfOnly: "მხოლოდ PDF ფაილი",
      menuUrlPlaceholder: "ან ვებ-გვერდის ბმული (URL)...",
      objectPhotos: "ობიექტის ფოტოები",
      menuMustBePdf: "მენიუ უნდა იყოს PDF ფაილი",
      menuUploadFailed: "მენიუს ატვირთვა ვერ მოხერხდა: {message}",
      enterTitle: "შეავსეთ ობიექტის დასახელება",
      chooseLocation: "აირჩიეთ ლოკაცია",
      chooseAvgCheck: "აირჩიეთ საშუალო ჩეკი",
      enterOperatingHours: "მიუთითეთ სამუშაო საათები",
    },
    CreateService: {
      pageTitle: "სერვისები და ხელოსნები",
      sectionSphereProfile: "სფერო და პროფილი",
      sectionDetails: "დეტალები და აღწერა",
      sectionSchedulePrice: "გრაფიკი, ფასი და კონტაქტი",
      nameOrCompany: "სახელი / კომპანია",
      namePlaceholder: "ნინო",
      experience: "გამოცდილება",
      experiencePlaceholder: "8 წელი",
      yearsSuffix: "წელი",
      serviceSphere: "მომსახურების სფერო",
      serviceTitle: "სათაური",
      titlePlaceholder: "პროფესიონალი დამლაგებელი",
      coverageZone: "დაფარვის ზონა",
      spokenLanguages: "სასაუბრო ენები",
      detailedDescription: "დეტალური აღწერა",
      descriptionPlaceholder:
        "ვასუფთავებ როგორც აპარტამენტებს, ისე კერძო კოტეჯებს...",
      workingHours: "სამუშაო საათები",
      mode247: "24/7 რეჟიმი",
      worksAtNight: "მუშაობს ღამითაც",
      startingPrice: "საწყისი ფასი / ტარიფი",
      priceUnitHour: "საათი",
      profilePhoto: "პროფილის ფოტო",
      uploadProfilePhoto: "ატვირთეთ პროფილის ფოტო",
      profilePhotoHint:
        "ატვირთეთ თქვენი ან კომპანიის ლოგოს ფოტო (სავალდებულოა)",
    },
    CreateTransport: {
      pageTitle: "ტრანსპორტი და ტრანსფერები",
      sectionRoutePrice: "მარშრუტი და ფასი",
      sectionEquipment: "აღჭურვილობა და ენები",
      driverName: "მძღოლის სახელი",
      driverPlaceholder: "გოგა მ.",
      vehicleMake: "მანქანის მარკა",
      chooseMake: "აირჩიე მარკა",
      searchMake: "მოძებნე მარკა...",
      transportType: "ტრანსპორტის ტიპი",
      vehicleCapacity: "რამდენ ადგილიანია მანქანა",
      vehicleColor: "მანქანის ფერი",
      chooseColor: "აირჩიე ფერი",
      descriptionPlaceholder: "დეტალები სერვისის შესახებ...",
      mainRoutes: "ძირითადი მარშრუტები",
      startingPrice: "საწყისი ფასი (GEL)",
      priceUnit: "ფასის ერთეული",
      vehicleEquipment: "მანქანის აღჭურვილობა",
      comfortAndServices: "კომფორტი და სერვისები",
      vehiclePhotos: "მანქანის ფოტოები",
      enterDriverName: "მიუთითეთ მძღოლის სახელი",
      enterCapacity: "მიუთითეთ ადგილების რაოდენობა",
      chooseRoute: "აირჩიეთ მინიმუმ ერთი მარშრუტი",
      enterPrice: "მიუთითეთ საწყისი ფასი",
    },
    CreateEntertainment: {
      pageTitle: "გართობა და აქტივობები",
      subtitle: "ტურიზმი, ტურები და ინვენტარის გაქირავება",
      sectionFeatures: "მახასიათებლები",
      sectionTariff: "ტარიფი",
      sectionContact: "კონტაქტი",
      title: "სათაური",
      titlePlaceholder: "ექსტრემალური ტური თოვლის ბურანით",
      entertainmentType: "გართობის ტიპი",
      category: "კატეგორია",
      zoneTrack: "ზონა / ტრასა",
      exactLocation: "ზუსტი ლოკაცია",
      descriptionLabel: "აღწერა (რას გთავაზობთ)",
      descriptionPlaceholder:
        "დაუვიწყარი 1 საათიანი ექსტრემალური ტური დიდველის დათოვლილ ტყეში...",
      duration: "ხანგრძლივობა",
      age: "ასაკი",
      audience: "ვისთვის არის",
      safetyConditions: "უსაფრთხოება და პირობები",
      safetyPlaceholder:
        "მაგ: ჩაიცვით შესაბამისი დასაცავი აღჭურვილობა, ტურს ახლავს პროფესიონალი ინსტრუქტორი",
      tariff: "ტარიფი (GEL)",
      priceGivenFor: "ფასი მოცემულია",
      uploadPhotos: "ფოტოების ატვირთვა",
      phone: "ტელეფონი",
    },
    CreateEmployment: {
      pageTitle: "დასაქმება ბაკურიანში",
      sectionSchedulePay: "გრაფიკი და ანაზღაურება",
      sectionConditions: "პირობები, აღწერა და მოთხოვნები",
      employer: "დამსაქმებელი / ობიექტი",
      employerPlaceholder: "რესტორანი 'პანორამა'",
      location: "ლოკაცია",
      position: "პოზიცია",
      positionPlaceholder: "მიმტანი / ბარმენი",
      employmentType: "დასაქმების ტიპი",
      salaryType: "ანაზღაურების ტიპი",
      salary: "ანაზღაურება (₾)",
      dailySalaryPlaceholder: "დღიური ანაზღაურება",
      accommodation: "საცხოვრებლით უზრუნველყოფა",
      meals: "კვებით უზრუნველყოფა",
      jobDescription: "სამუშაოს აღწერა",
      jobDescriptionPlaceholder:
        "ვეძებთ კომუნიკაბელურ და მოტივირებულ მიმტანებს...",
      requirements: "მოთხოვნები და კომპეტენციები",
      requirementsPlaceholder:
        "ინგლისური ან რუსული ენის სასაუბრო დონეზე ცოდნა...",
      preferredLanguages: "სასურველი ენები",
      workExperience: "სამუშაო გამოცდილება",
    },
    CreateSale: {
      pageTitle: "ყიდვა / გაყიდვა",
      sectionIdentity: "იდენტიფიკაცია და სტატუსი",
      sectionCondition: "მდგომარეობა და საინვესტიციო მეტრიკები",
      sectionFinance: "ფინანსები და ფართობი",
      sectionDetailsContact: "დეტალები და კონტაქტი",
      listingTitle: "სათაური",
      titleMaxHelper: "მაქსიმუმ {max} სიმბოლო",
      titlePlaceholder: "მაგ: საინვესტიციო აპარტამენტი დიდველზე...",
      propertyType: "ობიექტის ტიპი",
      locationZone: "ლოკაცია (ZONE)",
      constructionStatus: "მშენებლობის სტატუსი",
      handoverDate: "ჩაბარების დრო",
      cadastralCode: "საკადასტრო კოდი",
      cadastralHelper:
        "თუ ბინა დასრულებულია, შეიყვანეთ ბინის კოდი. თუ მშენებარეა - მიუთითეთ მიწის/პროექტის კოდი.",
      roomsCount: "ოთახების რაოდენობა",
      roomsPlaceholder: "მაგ: 1, 2, 3",
      exactLocation: "ზუსტი ლოკაცია",
      renovationStatus: "რემონტის მდგომარეობა",
      managementService: "მართვის სერვისი",
      expectedRoi: "მოსალოდნელი ROI (%)",
      totalArea: "საერთო ფართობი (კვ.მ)",
      priceUsd: "ფასი (USD)",
      photosRenders: "ფოტოები / რენდერები",
      descriptionPlaceholder: "დეტალური აღწერა ობიექტის შესახებ...",
      invalidTitle: "არასწორი სათაური",
      invalidLocation: "არასწორი მდებარეობა",
      enterCadastral: "მიუთითეთ საკადასტრო კოდი",
      invalidArea: "არასწორი ფართობი",
      invalidPrice: "არასწორი ფასი",
      soldReservedExceeds:
        "გაყიდული + ჯავშანი არ უნდა აღემატებოდეს ბინების საერთო რაოდენობას",
    },
  },
  en: {
    CreateHub: {
      title: "Add listing",
      subtitle: "Choose a category",
      categories: {
        rental: "Rentals",
        sale: "Buy / Sell",
        employment: "Employment",
        service: "Services",
        transport: "Transport",
        food: "Food",
        entertainment: "Entertainment",
      },
    },
    Wizard: { step: "Step" },
    CreateHeader: {
      addListing: "Add listing",
      balance: "Balance",
      cabinet: "Dashboard",
      signIn: "Sign in",
    },
    PhotoUploader: {
      skippedInvalid: "{count} file(s) skipped — JPG, PNG, WEBP only",
      skippedByLimit: "{count} file(s) skipped — max {max} photos",
      uploadPhotos: "Upload photos",
      dropHereOrClick: "Drop here or click",
      maxPhotos: "Max {max} photos",
      uploadPhotosAlt: "Upload photos",
      dropHereOrClickSelect: "Drop or select photos",
      photoCount: "{count} / {max} photos",
    },
    MediaUploader: {
      defaultLabel: "Media (image or video)",
      defaultHelper: "JPG / PNG / WEBP max 5MB or MP4 / WebM max 50MB",
      invalidFileType: "Invalid file type: {type}",
      posterMustBeImage: "Poster must be an image",
      fileTooLarge: "File too large. Max {mb}MB",
      uploadFailed: "Upload failed",
      fileUploadFailed: "File upload failed",
      error: "Error",
      delete: "Delete",
      uploading: "Uploading…",
      chooseFile: "Choose file",
      videoPoster: "Video poster",
      posterImageOnly: "Images only",
      videoPosterOptional: "Video poster (optional)",
      posterPreviewHint: "Preview before video loads",
      change: "Change",
      choose: "Choose",
    },
    BulkActionBar: {
      quickSelect: "Quick select",
      allAvailable: "Whole month available",
      allBlocked: "Whole month blocked",
      weekdaysOnly: "Weekdays only",
      weekendsOnly: "Sat–Sun only",
      blockNext7: "Block next 7 days",
    },
    AvailabilityWizard: {
      introTitle: "Select days and set prices for the next 30 days.",
      introBody:
        "Click or drag to select days, then set a price or block them. By default all days are available at the base price — {orange} price means it was changed.",
      orangeHighlight: "orange",
      availableCount: "{count} available",
      blockedCount: "{count} blocked",
      daysConfirmed: "{total} / 30 days confirmed",
      cancelSelection: "Cancel",
      selectedMixed: "{available} available • {blocked} blocked",
      selectedAvailable: "{count} days selected",
      selectedBlocked: "{count} blocked selected",
      avgPrice: "Average price: {price}₾",
      unblock: "Unblock ({count})",
      block: "Block ({count})",
      newPricePlaceholder: "New price",
      applyPrice: "Apply",
      resetPriceTitle: "Reset price to default",
      resetPrice: "Default",
      footerHint:
        "You can update the calendar and prices later from your dashboard.",
      booked: "Booked",
      blockedSelect: "Blocked — click to select",
      availablePrice: "Available, {price}₾",
    },
    CreateShared: {
      listingNotFound: "Listing not found",
      genericError: "Error. Please try again.",
      save: "Save",
      publishListing: "Publish listing",
      loading: "Loading...",
      basicInfo: "Basic information",
      contactInfo: "Contact information",
      description: "Description",
      phoneNumber: "Phone number",
      whatsappNumber: "WhatsApp number",
      whatsappOptional: "WhatsApp optional",
      optional: "Optional",
      chooseType: "Choose type",
      chooseZone: "Choose zone",
      choosePrice: "Choose price",
      choose: "Choose",
      delete: "Delete",
      showOnMap: "Show on map",
      pickOnMap: "Pick on map",
      minPhotos: "Minimum {count} photos",
      minPhotosShort: "Min. {count} photos",
      enterPhone: "Enter phone number",
      minPhotosRequired: "At least {count} photos required",
      uploadMinOnePhoto: "Upload at least one photo",
      eg: "e.g. {value}",
      sqm: "sq.m",
      or: "or",
      onlyUnderConstruction: "Under construction only",
    },
    ListingOptions: {
      foodAmenities: {
        has_kids_area: "Kids area",
        has_lounge: "Smoking zone",
        has_delivery: "Delivery",
        has_live_music: "Live music",
      },
      restaurantTypes: {
        restaurant: "Restaurant",
        cafe: "Café / confectionery",
        bar: "Bar / pub",
        fast_food: "Fast food",
        other: "Other",
      },
      cuisineTypes: {
        georgian: "Georgian",
        european: "European",
        asian: "Asian",
        mixed: "Mixed",
      },
      transportTypes: {
        minivan: "Minivan",
        taxi: "Taxi",
        microbus: "Microbus",
        other: "Other",
      },
      priceUnits: {
        whole_car: "Whole car",
        on_demand: "On demand",
        per_person: "Per person",
      },
      serviceSpheres: {
        cleaning: "Cleaning",
        handymen: "Handymen",
        staff: "Service staff",
        tourism: "Tourism",
        sales: "Sales / retail",
        other: "Other",
      },
      coverageZones: {
        all_bakuriani: "All Bakuriani",
        mitarbi: "Mitarbi",
        tsalgeri: "Tsalgeri",
      },
      languages: {
        ka: "Georgian",
        en: "English",
        ru: "Russian",
      },
      vehicleColors: {
        white: "White",
        black: "Black",
        gray: "Gray",
        silver: "Silver",
        red: "Red",
        blue: "Blue",
        light_blue: "Light blue",
        green: "Green",
        yellow: "Yellow",
        orange: "Orange",
        brown: "Brown",
        gold: "Gold",
        other: "Other",
      },
      transportFeatures: {
        ac: "Air conditioning",
        wifi: "Wi-Fi",
        usb: "USB charger",
        music: "Music",
        water: "Water",
        child_seat: "Child seat",
      },
      entertainmentTypes: {
        extreme: "Extreme",
        sport: "Sport",
        kids: "For kids",
        family: "For families",
        other: "Other",
      },
      entertainmentCategories: {
        inventory_rent: "Equipment rental",
        horses: "Horses",
        buggies: "Snowmobiles",
        quad_bikes: "Quad bikes",
        buggy: "Buggy",
        other: "Other",
      },
      durations: {
        "15min": "15 minutes",
        "30min": "30 minutes",
        "1h": "1 hour",
        "1h+": "1+ hours",
      },
      ageOptions: { any: "Any" },
      audienceOptions: {
        all: "For everyone",
        extreme_lovers: "Extreme lovers",
      },
      pricePerOptions: {
        "15min": "Per 15 min",
        "1h": "Per hour",
        full_day: "Full day",
      },
      employmentTypes: {
        full_time: "Full-time",
        part_time: "Part-time",
        flexible: "Flexible",
      },
      salaryTypes: {
        fixed: "Fixed",
        fixed_bonus: "Fixed + bonus/tips",
        commission: "Commission (%)",
        negotiable: "Negotiable",
      },
      experienceOptions: {
        preferred: "Preferred",
        not_required: "Not required",
        one_year: "1 year",
        one_plus_year: "1+ years",
      },
      accommodationOptions: {
        yes: "Yes",
        no: "No",
        negotiable: "Negotiable",
      },
      mealsOptions: {
        full: "Full board",
        single: "One meal",
        not_included: "Not included",
      },
      salePropertyTypes: {
        studio: "Studio",
        apartment: "Apartment",
        cottage: "Cottage",
        villa: "Land plot",
        hotel: "Hotel room",
      },
      constructionStatuses: {
        under_construction: "Under construction",
        completed: "Newly built / completed",
      },
    },
    CreateFood: {
      pageTitle: "Food & restaurants",
      sectionDetails: "Details & services",
      sectionMenuPhotos: "Menu & photos",
      objectTitle: "Venue name",
      titlePlaceholder: "e.g. Panorama Restaurant",
      restaurantType: "Restaurant type",
      cuisineType: "Cuisine type",
      locationZone: "Location (ZONE)",
      exactLocation: "Exact location",
      exactLocationPlaceholder: "e.g. near Central Park entrance",
      descriptionPlaceholder: "Detailed description of the restaurant...",
      avgCheck: "Average check per person",
      operatingHours: "Opening hours",
      hoursPlaceholder: "e.g. 10:00 - 20:00",
      extraDetails: "Additional details",
      menuOptional: "Menu (optional)",
      uploadMenu: "Upload menu",
      pdfOnly: "PDF files only",
      menuUrlPlaceholder: "Or website link (URL)...",
      objectPhotos: "Venue photos",
      menuMustBePdf: "Menu must be a PDF file",
      menuUploadFailed: "Menu upload failed: {message}",
      enterTitle: "Enter venue name",
      chooseLocation: "Choose location",
      chooseAvgCheck: "Choose average check",
      enterOperatingHours: "Enter opening hours",
    },
    CreateService: {
      pageTitle: "Services & handymen",
      sectionSphereProfile: "Sphere & profile",
      sectionDetails: "Details & description",
      sectionSchedulePrice: "Schedule, price & contact",
      nameOrCompany: "Name / company",
      namePlaceholder: "Nino",
      experience: "Experience",
      experiencePlaceholder: "8 years",
      yearsSuffix: "years",
      serviceSphere: "Service sphere",
      serviceTitle: "Title",
      titlePlaceholder: "Professional cleaner",
      coverageZone: "Coverage zone",
      spokenLanguages: "Spoken languages",
      detailedDescription: "Detailed description",
      descriptionPlaceholder: "I clean apartments and private cottages...",
      workingHours: "Working hours",
      mode247: "24/7 mode",
      worksAtNight: "Works at night too",
      startingPrice: "Starting price / rate",
      priceUnitHour: "hour",
      profilePhoto: "Profile photo",
      uploadProfilePhoto: "Upload profile photo",
      profilePhotoHint: "Upload your photo or company logo (required)",
    },
    CreateTransport: {
      pageTitle: "Transport & transfers",
      sectionRoutePrice: "Route & price",
      sectionEquipment: "Equipment & languages",
      driverName: "Driver name",
      driverPlaceholder: "Goga M.",
      vehicleMake: "Vehicle make",
      chooseMake: "Choose make",
      searchMake: "Search make...",
      transportType: "Transport type",
      vehicleCapacity: "Vehicle capacity (seats)",
      vehicleColor: "Vehicle color",
      chooseColor: "Choose color",
      descriptionPlaceholder: "Details about the service...",
      mainRoutes: "Main routes",
      startingPrice: "Starting price (GEL)",
      priceUnit: "Price unit",
      vehicleEquipment: "Vehicle equipment",
      comfortAndServices: "Comfort & services",
      vehiclePhotos: "Vehicle photos",
      enterDriverName: "Enter driver name",
      enterCapacity: "Enter number of seats",
      chooseRoute: "Select at least one route",
      enterPrice: "Enter starting price",
    },
    CreateEntertainment: {
      pageTitle: "Entertainment & activities",
      subtitle: "Tourism, tours & equipment rental",
      sectionFeatures: "Features",
      sectionTariff: "Tariff",
      sectionContact: "Contact",
      title: "Title",
      titlePlaceholder: "Extreme snowmobile tour",
      entertainmentType: "Entertainment type",
      category: "Category",
      zoneTrack: "Zone / track",
      exactLocation: "Exact location",
      descriptionLabel: "Description (what you offer)",
      descriptionPlaceholder:
        "Unforgettable 1-hour extreme tour in snowy Didveli forest...",
      duration: "Duration",
      age: "Age",
      audience: "Audience",
      safetyConditions: "Safety & conditions",
      safetyPlaceholder:
        "e.g. wear proper protective gear; tour led by a professional instructor",
      tariff: "Tariff (GEL)",
      priceGivenFor: "Price is for",
      uploadPhotos: "Upload photos",
      phone: "Phone",
    },
    CreateEmployment: {
      pageTitle: "Jobs in Bakuriani",
      sectionSchedulePay: "Schedule & compensation",
      sectionConditions: "Conditions, description & requirements",
      employer: "Employer / venue",
      employerPlaceholder: "Panorama Restaurant",
      location: "Location",
      position: "Position",
      positionPlaceholder: "Waiter / bartender",
      employmentType: "Employment type",
      salaryType: "Compensation type",
      salary: "Salary (₾)",
      dailySalaryPlaceholder: "Daily pay",
      accommodation: "Accommodation provided",
      meals: "Meals provided",
      jobDescription: "Job description",
      jobDescriptionPlaceholder:
        "We are looking for communicative and motivated waiters...",
      requirements: "Requirements & skills",
      requirementsPlaceholder: "Conversational English or Russian...",
      preferredLanguages: "Preferred languages",
      workExperience: "Work experience",
    },
    CreateSale: {
      pageTitle: "Buy / Sell",
      sectionIdentity: "Identity & status",
      sectionCondition: "Condition & investment metrics",
      sectionFinance: "Finance & area",
      sectionDetailsContact: "Details & contact",
      listingTitle: "Title",
      titleMaxHelper: "Maximum {max} characters",
      titlePlaceholder: "e.g. Investment apartment in Didveli...",
      propertyType: "Property type",
      locationZone: "Location (ZONE)",
      constructionStatus: "Construction status",
      handoverDate: "Handover date",
      cadastralCode: "Cadastral code",
      cadastralHelper:
        "If completed, enter the unit code. If under construction — land/project code.",
      roomsCount: "Number of rooms",
      roomsPlaceholder: "e.g. 1, 2, 3",
      exactLocation: "Exact location",
      renovationStatus: "Renovation status",
      managementService: "Management service",
      expectedRoi: "Expected ROI (%)",
      totalArea: "Total area (sq.m)",
      priceUsd: "Price (USD)",
      photosRenders: "Photos / renders",
      descriptionPlaceholder: "Detailed description of the property...",
      invalidTitle: "Invalid title",
      invalidLocation: "Invalid location",
      enterCadastral: "Enter cadastral code",
      invalidArea: "Invalid area",
      invalidPrice: "Invalid price",
      soldReservedExceeds:
        "Sold + reserved must not exceed total number of units",
    },
  },
  ru: {
    CreateHub: {
      title: "Добавить объявление",
      subtitle: "Выберите категорию",
      categories: {
        rental: "Аренда",
        sale: "Покупка / продажа",
        employment: "Работа",
        service: "Услуги",
        transport: "Транспорт",
        food: "Еда",
        entertainment: "Развлечения",
      },
    },
    Wizard: { step: "Шаг" },
    CreateHeader: {
      addListing: "Добавить объявление",
      balance: "Баланс",
      cabinet: "Кабинет",
      signIn: "Войти",
    },
    PhotoUploader: {
      skippedInvalid: "{count} файл(ов) пропущено — только JPG, PNG, WEBP",
      skippedByLimit: "{count} файл(ов) пропущено — макс. {max} фото",
      uploadPhotos: "Загрузить фото",
      dropHereOrClick: "Перетащите сюда или нажмите",
      maxPhotos: "Макс. {max} фото",
      uploadPhotosAlt: "Загрузите фото",
      dropHereOrClickSelect: "Перетащите или выберите фото",
      photoCount: "{count} / {max} фото",
    },
    MediaUploader: {
      defaultLabel: "Медиа (изображение или видео)",
      defaultHelper: "JPG / PNG / WEBP макс. 5MB или MP4 / WebM макс. 50MB",
      invalidFileType: "Неверный тип файла: {type}",
      posterMustBeImage: "Постер должен быть изображением",
      fileTooLarge: "Файл слишком большой. Макс. {mb}MB",
      uploadFailed: "Загрузка не удалась",
      fileUploadFailed: "Не удалось загрузить файл",
      error: "Ошибка",
      delete: "Удалить",
      uploading: "Загрузка…",
      chooseFile: "Выбрать файл",
      videoPoster: "Постер видео",
      posterImageOnly: "Только изображения",
      videoPosterOptional: "Постер видео (необязательно)",
      posterPreviewHint: "Превью до загрузки видео",
      change: "Изменить",
      choose: "Выбрать",
    },
    BulkActionBar: {
      quickSelect: "Быстрый выбор",
      allAvailable: "Весь месяц доступен",
      allBlocked: "Весь месяц занят",
      weekdaysOnly: "Только будни",
      weekendsOnly: "Только сб–вс",
      blockNext7: "Заблокировать 7 дней",
    },
    AvailabilityWizard: {
      introTitle: "Выберите дни и установите цены на следующие 30 дней.",
      introBody:
        "Кликните или перетащите для выбора дней, затем установите цену или заблокируйте. По умолчанию все дни доступны по базовой цене — {orange} цена означает изменение.",
      orangeHighlight: "оранжевый",
      availableCount: "{count} доступно",
      blockedCount: "{count} занято",
      daysConfirmed: "{total} / 30 дней подтверждено",
      cancelSelection: "Отмена",
      selectedMixed: "{available} доступно • {blocked} занято",
      selectedAvailable: "{count} дней выбрано",
      selectedBlocked: "{count} занятых выбрано",
      avgPrice: "Средняя цена: {price}₾",
      unblock: "Разблокировать ({count})",
      block: "Заблокировать ({count})",
      newPricePlaceholder: "Новая цена",
      applyPrice: "Применить",
      resetPriceTitle: "Сбросить цену по умолчанию",
      resetPrice: "По умолчанию",
      footerHint: "Календарь и цены можно обновить позже в личном кабинете.",
      booked: "Бронь",
      blockedSelect: "Занято — нажмите для выбора",
      availablePrice: "Доступно, {price}₾",
    },
    CreateShared: {
      listingNotFound: "Объявление не найдено",
      genericError: "Ошибка. Попробуйте снова.",
      save: "Сохранить",
      publishListing: "Опубликовать объявление",
      loading: "Загрузка...",
      basicInfo: "Основная информация",
      contactInfo: "Контактная информация",
      description: "Описание",
      phoneNumber: "Номер телефона",
      whatsappNumber: "WhatsApp",
      whatsappOptional: "WhatsApp необязательно",
      optional: "Необязательно",
      chooseType: "Выберите тип",
      chooseZone: "Выберите зону",
      choosePrice: "Выберите цену",
      choose: "Выберите",
      delete: "Удалить",
      showOnMap: "Показать на карте",
      pickOnMap: "Выбрать на карте",
      minPhotos: "Минимум {count} фото",
      minPhotosShort: "Мин. {count} фото",
      enterPhone: "Укажите номер телефона",
      minPhotosRequired: "Минимум {count} фото обязательно",
      uploadMinOnePhoto: "Загрузите хотя бы одно фото",
      eg: "напр. {value}",
      sqm: "кв.м",
      or: "или",
      onlyUnderConstruction: "Только строящиеся",
    },
    ListingOptions: {
      foodAmenities: {
        has_kids_area: "Детская зона",
        has_lounge: "Зона для курения",
        has_delivery: "Доставка",
        has_live_music: "Живая музыка",
      },
      restaurantTypes: {
        restaurant: "Ресторан",
        cafe: "Кафе / кондитерская",
        bar: "Бар / паб",
        fast_food: "Фастфуд",
        other: "Другое",
      },
      cuisineTypes: {
        georgian: "Грузинская",
        european: "Европейская",
        asian: "Азиатская",
        mixed: "Смешанная",
      },
      transportTypes: {
        minivan: "Минивэн",
        taxi: "Такси",
        microbus: "Микроавтобус",
        other: "Другое",
      },
      priceUnits: {
        whole_car: "Вся машина",
        on_demand: "По вызову",
        per_person: "За человека",
      },
      serviceSpheres: {
        cleaning: "Уборка",
        handymen: "Мастера",
        staff: "Обслуживающий персонал",
        tourism: "Туризм",
        sales: "Продажи / торговля",
        other: "Другое",
      },
      coverageZones: {
        all_bakuriani: "Весь Бакуриани",
        mitarbi: "Митарби",
        tsalgeri: "Цалgeri",
      },
      languages: {
        ka: "Грузинский",
        en: "Английский",
        ru: "Русский",
      },
      vehicleColors: {
        white: "Белый",
        black: "Чёрный",
        gray: "Серый",
        silver: "Серебристый",
        red: "Красный",
        blue: "Синий",
        light_blue: "Гolubой",
        green: "Зелёный",
        yellow: "Жёлтый",
        orange: "Оранжевый",
        brown: "Коричневый",
        gold: "Золотой",
        other: "Другое",
      },
      transportFeatures: {
        ac: "Кондиционер",
        wifi: "Wi-Fi",
        usb: "USB-зарядка",
        music: "Музыка",
        water: "Вода",
        child_seat: "Детское кресло",
      },
      entertainmentTypes: {
        extreme: "Экстремальный",
        sport: "Спортивный",
        kids: "Для детей",
        family: "Для семей",
        other: "Другое",
      },
      entertainmentCategories: {
        inventory_rent: "Аренда инвентаря",
        horses: "Лошади",
        buggies: "Снегоходы",
        quad_bikes: "Квадроциклы",
        buggy: "Багги",
        other: "Другое",
      },
      durations: {
        "15min": "15 минут",
        "30min": "30 минут",
        "1h": "1 час",
        "1h+": "1+ часа",
      },
      ageOptions: { any: "Любой" },
      audienceOptions: {
        all: "Для всех",
        extreme_lovers: "Любители экстрима",
      },
      pricePerOptions: {
        "15min": "За 15 мин",
        "1h": "За час",
        full_day: "За полный день",
      },
      employmentTypes: {
        full_time: "Полная занятость",
        part_time: "Частичная занятость",
        flexible: "Гибкий график",
      },
      salaryTypes: {
        fixed: "Фиксированная",
        fixed_bonus: "Фикс + бонус/чаевые",
        commission: "Процент (%)",
        negotiable: "По договорённости",
      },
      experienceOptions: {
        preferred: "Желательно",
        not_required: "Не обязательно",
        one_year: "1 год",
        one_plus_year: "1+ года",
      },
      accommodationOptions: {
        yes: "Да",
        no: "Нет",
        negotiable: "По договорённости",
      },
      mealsOptions: {
        full: "Полный пансион",
        single: "Одно питание",
        not_included: "Не включено",
      },
      salePropertyTypes: {
        studio: "Студия",
        apartment: "Апартаменты",
        cottage: "Коттедж",
        villa: "Земельный участок",
        hotel: "Гостиничный номер",
      },
      constructionStatuses: {
        under_construction: "Строится",
        completed: "Новострой / сдан",
      },
    },
    CreateFood: {
      pageTitle: "Еда и рестораны",
      sectionDetails: "Детали и услуги",
      sectionMenuPhotos: "Меню и фото",
      objectTitle: "Название заведения",
      titlePlaceholder: "напр. Ресторан Панорама",
      restaurantType: "Тип ресторана",
      cuisineType: "Тип кухни",
      locationZone: "Локация (ZONE)",
      exactLocation: "Точная локация",
      exactLocationPlaceholder: "напр. у входа в центральный парк",
      descriptionPlaceholder: "Подробное описание ресторана...",
      avgCheck: "Средний чек на человека",
      operatingHours: "Часы работы",
      hoursPlaceholder: "напр. 10:00 - 20:00",
      extraDetails: "Дополнительные детали",
      menuOptional: "Меню (необязательно)",
      uploadMenu: "Загрузить меню",
      pdfOnly: "Только PDF",
      menuUrlPlaceholder: "Или ссылка на сайт (URL)...",
      objectPhotos: "Фото заведения",
      menuMustBePdf: "Меню должно быть в формате PDF",
      menuUploadFailed: "Не удалось загрузить меню: {message}",
      enterTitle: "Введите название заведения",
      chooseLocation: "Выберите локацию",
      chooseAvgCheck: "Выберите средний чек",
      enterOperatingHours: "Укажите часы работы",
    },
    CreateService: {
      pageTitle: "Услуги и мастера",
      sectionSphereProfile: "Сфера и профиль",
      sectionDetails: "Детали и описание",
      sectionSchedulePrice: "График, цена и контакт",
      nameOrCompany: "Имя / компания",
      namePlaceholder: "Нино",
      experience: "Опыт",
      experiencePlaceholder: "8 лет",
      yearsSuffix: "лет",
      serviceSphere: "Сфера услуг",
      serviceTitle: "Заголовок",
      titlePlaceholder: "Профессиональный клинер",
      coverageZone: "Зона покрытия",
      spokenLanguages: "Языки общения",
      detailedDescription: "Подробное описание",
      descriptionPlaceholder: "Убираю квартиры и частные коттеджи...",
      workingHours: "Часы работы",
      mode247: "Режим 24/7",
      worksAtNight: "Работает ночью",
      startingPrice: "Начальная цена / тариф",
      priceUnitHour: "час",
      profilePhoto: "Фото профиля",
      uploadProfilePhoto: "Загрузить фото профиля",
      profilePhotoHint: "Загрузите фото или логотип компании (обязательно)",
    },
    CreateTransport: {
      pageTitle: "Транспорт и трансферы",
      sectionRoutePrice: "Маршрут и цена",
      sectionEquipment: "Оборудование и языки",
      driverName: "Имя водителя",
      driverPlaceholder: "Гога М.",
      vehicleMake: "Марка автомобиля",
      chooseMake: "Выберите марку",
      searchMake: "Поиск марки...",
      transportType: "Тип транспорта",
      vehicleCapacity: "Вместимость (мест)",
      vehicleColor: "Цвет автомобиля",
      chooseColor: "Выберите цвет",
      descriptionPlaceholder: "Детали об услуге...",
      mainRoutes: "Основные маршруты",
      startingPrice: "Начальная цена (GEL)",
      priceUnit: "Единица цены",
      vehicleEquipment: "Оборудование",
      comfortAndServices: "Комфорт и услуги",
      vehiclePhotos: "Фото автомобиля",
      enterDriverName: "Укажите имя водителя",
      enterCapacity: "Укажите количество мест",
      chooseRoute: "Выберите хотя бы один маршрут",
      enterPrice: "Укажите начальную цену",
    },
    CreateEntertainment: {
      pageTitle: "Развлечения и активности",
      subtitle: "Туризм, туры и аренда инвентаря",
      sectionFeatures: "Характеристики",
      sectionTariff: "Тариф",
      sectionContact: "Контакт",
      title: "Заголовок",
      titlePlaceholder: "Экстремальный тур на снегоходе",
      entertainmentType: "Тип развлечения",
      category: "Категория",
      zoneTrack: "Зона / трасса",
      exactLocation: "Точная локация",
      descriptionLabel: "Описание (что предлагаете)",
      descriptionPlaceholder:
        "Незабываемый час экстремального тура в снежном лесу Дидveli...",
      duration: "Длительность",
      age: "Возраст",
      audience: "Для кого",
      safetyConditions: "Безопасность и условия",
      safetyPlaceholder:
        "напр. наденьте защиту; тур с профессиональным инструктором",
      tariff: "Тариф (GEL)",
      priceGivenFor: "Цена указана за",
      uploadPhotos: "Загрузить фото",
      phone: "Телефон",
    },
    CreateEmployment: {
      pageTitle: "Работа в Бакуриани",
      sectionSchedulePay: "График и оплата",
      sectionConditions: "Условия, описание и требования",
      employer: "Работодатель / объект",
      employerPlaceholder: "Ресторан «Панорама»",
      location: "Локация",
      position: "Должность",
      positionPlaceholder: "Официант / бармен",
      employmentType: "Тип занятости",
      salaryType: "Тип оплаты",
      salary: "Зарплата (₾)",
      dailySalaryPlaceholder: "Дневная оплата",
      accommodation: "Предоставляется жильё",
      meals: "Предоставляется питание",
      jobDescription: "Описание работы",
      jobDescriptionPlaceholder:
        "Ищем коммуникабельных и мотивированных официантов...",
      requirements: "Требования и навыки",
      requirementsPlaceholder: "Разговорный английский или русский...",
      preferredLanguages: "Предпочтительные языки",
      workExperience: "Опыт работы",
    },
    CreateSale: {
      pageTitle: "Покупка / продажа",
      sectionIdentity: "Идентификация и статус",
      sectionCondition: "Состояние и инвестиционные метрики",
      sectionFinance: "Финансы и площадь",
      sectionDetailsContact: "Детали и контакт",
      listingTitle: "Заголовок",
      titleMaxHelper: "Максимум {max} символов",
      titlePlaceholder: "напр. Инвестиционные апартаменты в Didveli...",
      propertyType: "Тип объекта",
      locationZone: "Локация (ZONE)",
      constructionStatus: "Статус строительства",
      handoverDate: "Срок сдачи",
      cadastralCode: "Кадастровый код",
      cadastralHelper:
        "Если сдан — код квартиры. Если строится — код земли/проекта.",
      roomsCount: "Количество комнат",
      roomsPlaceholder: "напр. 1, 2, 3",
      exactLocation: "Точная локация",
      renovationStatus: "Состояние ремонта",
      managementService: "Управляющая компания",
      expectedRoi: "Ожидаемый ROI (%)",
      totalArea: "Общая площадь (кв.м)",
      priceUsd: "Цена (USD)",
      photosRenders: "Фото / рендеры",
      descriptionPlaceholder: "Подробное описание объекта...",
      invalidTitle: "Неверный заголовок",
      invalidLocation: "Неверная локация",
      enterCadastral: "Укажите кадастровый код",
      invalidArea: "Неверная площадь",
      invalidPrice: "Неверная цена",
      soldReservedExceeds:
        "Продано + забронировано не должно превышать общее число квартир",
    },
  },
});
