#!/usr/bin/env python3
"""Code-map generator + memory-bank anchor validator for MyBakuriani.

Two jobs, one dependency-light script (stdlib only):

  1. GENERATE  `python3 scripts/gen_code_map.py`
     Regenerates memory-bank/generated/symbols.md — a module -> symbol
     inventory (file:line for every export) plus internal import edges,
     scoped to src/ and supabase/functions/.

  2. CHECK     `python3 scripts/gen_code_map.py --check`
     Validates that every `path/file:symbol` anchor written inside
     memory-bank/*.md still resolves: the file exists AND the symbol string
     is present. Grep-based, so it works across .ts/.tsx/.sql/.mjs alike
     (a migration RPC, an i18n script, a TS export). Exit 1 on any dangler.

Output/exit convention mirrors scripts/i18n-scope.mjs:
  "[gen_code_map] OK — ..."   on success
  "[gen_code_map] ..." to stderr + exit 1 on failure.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MEMORY_BANK = ROOT / "memory-bank"
SYMBOLS_OUT = MEMORY_BANK / "generated" / "symbols.md"

# Directories scanned for the symbol inventory, in area order.
SCAN_ROOTS: list[tuple[str, Path, tuple[str, ...]]] = [
    ("api", ROOT / "src" / "app" / "api", (".ts", ".tsx")),
    ("api", ROOT / "src" / "app" / "actions", (".ts", ".tsx")),
    ("web", ROOT / "src" / "components", (".ts", ".tsx")),
    ("i18n", ROOT / "src" / "i18n", (".ts", ".tsx")),
    ("lib", ROOT / "src" / "lib", (".ts", ".tsx")),
    ("edge", ROOT / "supabase" / "functions", (".ts",)),
]
# src/app/[locale] is scanned separately so we can exclude api/actions.
WEB_APP_ROOT = ROOT / "src" / "app"

EXPORT_RE = re.compile(
    r"^export\s+(?:default\s+)?"
    r"(?:async\s+)?"
    r"(?:(?:const|let|var|function|class|type|interface|enum)\s+)"
    r"([A-Za-z_$][\w$]*)"
)
EXPORT_BRACE_RE = re.compile(r"^export\s*\{([^}]*)\}")
IMPORT_RE = re.compile(r"""^import\s+(?:type\s+)?.*?from\s+['"]([^'"]+)['"]""")

# Anchor grammar: `<relpath-with-a-slash-and-extension>:<symbol>` inside backticks.
ANCHOR_RE = re.compile(
    r"`([A-Za-z0-9_./\[\]\-]+\.[A-Za-z0-9]+):([A-Za-z0-9_.$\[\]]+)`"
)


def iter_files(root: Path, exts: tuple[str, ...]):
    if not root.exists():
        return
    for p in sorted(root.rglob("*")):
        if p.is_file() and p.suffix in exts:
            yield p


def web_app_files():
    """src/app/**/*.tsx|ts, excluding api/ and actions/ (their own area)."""
    api = ROOT / "src" / "app" / "api"
    actions = ROOT / "src" / "app" / "actions"
    for p in iter_files(WEB_APP_ROOT, (".ts", ".tsx")):
        if api in p.parents or actions in p.parents:
            continue
        yield p


def collect_symbols(path: Path):
    exports: list[tuple[str, int]] = []
    imports: set[str] = set()
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return exports, imports
    for i, line in enumerate(lines, 1):
        s = line.strip()
        m = EXPORT_RE.match(s)
        if m:
            exports.append((m.group(1), i))
            continue
        mb = EXPORT_BRACE_RE.match(s)
        if mb:
            for name in mb.group(1).split(","):
                name = name.strip().split(" as ")[-1].strip()
                if name and name != "*":
                    exports.append((name, i))
            continue
        if s.startswith("export default"):
            exports.append(("default", i))
        mi = IMPORT_RE.match(s)
        if mi:
            spec = mi.group(1)
            # Keep only internal edges (alias or relative), drop node_modules/URLs.
            if spec.startswith("@/") or spec.startswith("."):
                imports.add(spec)
    return exports, imports


def generate() -> int:
    # Build (area, file) -> (exports, imports), deduping web_app + components.
    seen: set[Path] = set()
    by_area: dict[str, list[tuple[Path, list, set]]] = {}

    def add(area: str, files):
        for p in files:
            if p in seen:
                continue
            seen.add(p)
            exports, imports = collect_symbols(p)
            by_area.setdefault(area, []).append((p, exports, imports))

    add("web", web_app_files())
    for area, root, exts in SCAN_ROOTS:
        add(area, iter_files(root, exts))

    total_files = sum(len(v) for v in by_area.values())
    total_syms = sum(len(e) for v in by_area.values() for _, e, _ in v)

    out: list[str] = []
    out.append("# Generated symbol inventory")
    out.append("")
    out.append(
        "> AUTO-GENERATED by `scripts/gen_code_map.py`. Do not edit by hand — "
        "run `python3 scripts/gen_code_map.py` to regenerate."
    )
    out.append(
        f"> Scope: `src/` + `supabase/functions/`. {total_files} modules, "
        f"{total_syms} exported symbols."
    )
    out.append("")
    out.append(
        "Each entry: exported symbols with `file:line`, then internal import "
        "edges (alias `@/` or relative). Grouped by area (see "
        "`../areas/`)."
    )
    out.append("")

    for area in ("web", "lib", "i18n", "api", "edge"):
        entries = by_area.get(area, [])
        if not entries:
            continue
        out.append(f"## {area}")
        out.append("")
        for p, exports, imports in sorted(entries, key=lambda t: str(t[0])):
            rel = p.relative_to(ROOT).as_posix()
            out.append(f"### `{rel}`")
            if exports:
                syms = ", ".join(f"`{n}` ({ln})" for n, ln in exports)
                out.append(f"- exports: {syms}")
            else:
                out.append("- exports: _(none)_")
            if imports:
                edges = ", ".join(f"`{spec}`" for spec in sorted(imports))
                out.append(f"- imports: {edges}")
            out.append("")

    SYMBOLS_OUT.parent.mkdir(parents=True, exist_ok=True)
    SYMBOLS_OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(
        f"[gen_code_map] OK — wrote {SYMBOLS_OUT.relative_to(ROOT)} "
        f"({total_files} modules, {total_syms} symbols)."
    )
    return 0


def symbol_present(text: str, symbol: str) -> bool:
    # Whole-word match, not substring: a rename `requireAdmin` ->
    # `requireAdminSession` must NOT keep resolving the stale `requireAdmin`
    # anchor — catching that staleness is the whole point of --check.
    if re.search(r"\b" + re.escape(symbol) + r"\b", text):
        return True
    # Fallback: match the head identifier as a whole word (handles `a.b.c`
    # anchors where only `a` literally appears in the source).
    head = re.split(r"[.\[]", symbol)[0]
    if not head or head == symbol:
        return False
    return re.search(r"\b" + re.escape(head) + r"\b", text) is not None


def check() -> int:
    if not MEMORY_BANK.exists():
        print("[gen_code_map] memory-bank/ not found", file=sys.stderr)
        return 1

    md_files = [
        p for p in sorted(MEMORY_BANK.rglob("*.md"))
        if p.name != "symbols.md"  # generated file references itself; skip
    ]
    dangling: list[str] = []
    checked = 0
    cache: dict[Path, str | None] = {}

    for md in md_files:
        text = md.read_text(encoding="utf-8", errors="replace")
        for m in ANCHOR_RE.finditer(text):
            relpath, symbol = m.group(1), m.group(2)
            checked += 1
            target = ROOT / relpath
            where = f"{md.relative_to(ROOT)} -> `{relpath}:{symbol}`"
            if target not in cache:
                cache[target] = (
                    target.read_text(encoding="utf-8", errors="replace")
                    if target.is_file()
                    else None
                )
            content = cache[target]
            if content is None:
                dangling.append(f"{where}  (file missing)")
            elif not symbol_present(content, symbol):
                dangling.append(f"{where}  (symbol not found)")

    if dangling:
        print(
            f"[gen_code_map] {len(dangling)} dangling anchor(s):",
            file=sys.stderr,
        )
        for d in dangling:
            print(f"  {d}", file=sys.stderr)
        return 1

    print(
        f"[gen_code_map] OK — all {checked} memory-bank anchors resolve."
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="validate memory-bank anchors instead of generating.",
    )
    args = ap.parse_args()
    return check() if args.check else generate()


if __name__ == "__main__":
    raise SystemExit(main())
